default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: mofdb2_development
  password: rootrootroot
  username: root
  socket: <%= ENV['SOCKET'] %>

production:
  <<: *default
  database: mofdb2_production
  username: mofdb
  password: <%= ENV['MOFDB2_DATABASE_PASSWORD'] %>
  socket: <%= ENV['SOCKET'] %>

