default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: mofdb2
#  database: mofdb2_testing
  password: admin
  username: admin
  socket: <%= ENV['SOCKET'] %>

production:
  <<: *default
  database: mofdb2
  username: mofdb
  password: <%= Rails.application.credentials.prod_mysql_pass %>
  socket: <%= ENV['SOCKET'] %>

