default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 100 } %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: mofdb2
  password: admin
  username: admin
  socket: <%= ENV['SOCKET'] %>

test:
  <<: *default
  adapter: mysql2
  database: mofdb2_test
  password: admin
  username: admin
  host: mysql://127.0.0.1:3306
#  socket: <%#= ENV['SOCKET'] %>


production:
  <<: *default
  database: mofdb2_production
  username: mofdb
  password: <%= Rails.application.credentials.prod_mysql_pass %>
  socket: <%= ENV['SOCKET'] %>
  timeout: 60

